###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Infernus",
    "number": "12-34-5678901"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "12-34-5678901"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Eric Sparrow"
}

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6079f0c3c972bb30b076da61

###

DELETE http://localhost:3001/api/persons/607a55b5f5f8990134df571f

###

PUT http://localhost:3001/api/persons/6079c9291d40a925b856192c HTTP/1.1
content-type: application/json

{
    "name": "BF Injection",
    "number": "55-55-1234567"
}